services:
  site:
    image: ghcr.io/mythal/boluo-mono/site:nightly
    build:
      context: .
      dockerfile: ./apps/site/Dockerfile

  server:
    image: ghcr.io/mythal/boluo-mono/server:nightly
    build:
      dockerfile: ./server/Dockerfile
