// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Channel } from './Channel';
import type { Member } from './Member';
import type { Message } from './Message';
import type { Preview } from './Preview';
import type { SpaceWithRelated } from './SpaceWithRelated';
import type { UserStatus } from './UserStatus';

export type EventBody =
  | { type: 'NEW_MESSAGE'; channel_id: string; message: Message }
  | { type: 'MESSAGE_DELETED'; message_id: string; channel_id: string }
  | { type: 'MESSAGE_EDITED'; channel_id: string; message: Message }
  | { type: 'MESSAGE_PREVIEW'; channel_id: string; preview: Preview }
  | { type: 'CHANNEL_DELETED'; channel_id: string }
  | { type: 'CHANNEL_EDITED'; channel_id: string; channel: Channel }
  | { type: 'MEMBERS'; channel_id: string; members: Array<Member> }
  | { type: 'INITIALIZED' }
  | {
    type: 'STATUS_MAP';
    status_map: Record<string, UserStatus>;
    space_id: string;
  }
  | { type: 'SPACE_UPDATED'; space_with_related: SpaceWithRelated }
  | { type: 'APP_UPDATED' };
