name: Build Images
on:
  push:
    branches:
      - master
      - production
jobs:
  site:
    name: site
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build apps/site image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: apps/site/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/site:${{ github.ref_name }}

  server:
    name: server
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build server image
        uses: docker/build-push-action@v2
        with:
          push: true
          file: server/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/server:${{ github.ref_name }}
