name: Nightly images
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Push to registery
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build apps/site image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: apps/site/Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}/site:nightly
